apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    environment: dev
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
    - nodePort: 30008
      port: 80
      targetPort: 8080